swagger: '2.0'
info:
    title: Football Club API
    description: Football Club API
    version: 1.0.0
host: football-club-api.vercel.app
basePath: /
schemes:
    - https
definitions:
    Status:
        type: integer
    Metadata:
        type: object
        properties:
            count:
                type: integer
    Player:
        properties:
            _id:
                type: string
            first_name:
                type: string
            last_name:
                type: string
            date_of_birth:
                type: string
            squad_number:
                type: integer
            position:
                type: string
            nationality:
                type: string
            slug:
                type: string
            is_captain:
                type: boolean
            is_vice_captain:
                type: boolean
            on_loan_from:
                type: string
            on_loan_to:
                type: string
    PlayersResponse:
        type: object
        properties:
            status:
                $ref: '#/definitions/Status'
            metadata:
                $ref: '#/definitions/Metadata'
            data:
                type: array
                items:
                    $ref: '#/definitions/Player'
paths:
    /players:
        get:
            summary: Returns all players, ordered by last_name in ascending order
            produces:
                - application/json
            responses:
                200:
                    description: Array of players.
                    schema:
                        $ref: '#/definitions/PlayersResponse'
    /players/{slug}:
        get:
            summary: Returns single player by slug (e.g. firstName-lastName)
            parameters:
                - name: james-collins
                  in: path
                  description: Slug of the player's name (e.g. firstName-lastName)
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                200:
                    description: Array of players with single item
                    schema:
                    $ref: '#/definitions/PlayersResponse'

    /players/captain:
        get:
            summary: Returns current Team Captain
            produces:
                - application/json
            responses:
                200:
                    description: Array of players with single item where is_captain is true
                    schema:
                        $ref: '#/definitions/PlayersResponse'
    /players/vicecaptain:
        get:
            summary: Returns current Team Vice-Captain
            produces:
                - application/json
            responses:
                200:
                    description: Array of players with single item where is_vice_captain is true
                    schema:
                        $ref: '#/definitions/PlayersResponse'
    /players/loan:
        get:
            summary: Returns all loan players
            produces:
                - application/json
            responses:
                200:
                    description: Array of players where they are either loaned into or out of the club
                    schema:
                        $ref: '#/definitions/PlayersResponse'
    /players/loan/in:
        get:
            summary: Returns all loan players
            produces:
                - application/json
            responses:
                200:
                    description: Array of players loaned into the club from other clubs
                    schema:
                        $ref: '#/definitions/PlayersResponse'
    /players/loan/out:
        get:
            summary: Returns all loan players
            produces:
                - application/json
            responses:
                200:
                    description: Array of players loaned out of the club to other clubs
                    schema:
                        $ref: '#/definitions/PlayersResponse'
