swagger: '2.0'
info:
    title: Football Club API
    description: Football Club API
    version: 1.0.0
host: football-club-api.vercel.app
basePath: /
schemes:
    - https
definitions:
    Status:
        type: integer
    Metadata:
        type: object
        properties:
            count:
                type: integer
    Player:
        properties:
            _id:
                type: string
            first_name:
                type: string
            last_name:
                type: string
            date_of_birth:
                type: string
            squad_number:
                type: integer
            position:
                type: string
            nationality:
                type: string
            slug:
                type: string
            is_captain:
                type: boolean
            is_vice_captain:
                type: boolean
            on_loan_from:
                type: string
            on_loan_to:
                type: string
    PlayersResponse:
        type: object
        properties:
            status:
                $ref: '#/definitions/Status'
            metadata:
                $ref: '#/definitions/Metadata'
            data:
                type: array
                items:
                    $ref: '#/definitions/Player'
    Staff:
        properties:
            _id:
                type: string
            first_name:
                type: string
            last_name:
                type: string
            date_of_birth:
                type: string
            role:
                type: string
            nationality:
                type: string
            slug:
                type: string
    StaffResponse:
        type: object
        properties:
            status:
                $ref: '#/definitions/Status'
            metadata:
                $ref: '#/definitions/Metadata'
            data:
                type: array
                items:
                    $ref: '#/definitions/Staff'
paths:
    /players:
        get:
            tags:
                - Players
            summary: Returns all players, ordered by last_name in ascending order
            produces:
                - application/json
            responses:
                200:
                    description: List of players.
                    schema:
                        $ref: '#/definitions/PlayersResponse'
        post:
            tags:
                - Players
            summary: Create a new player
            responses:
                201:
                    description: The created player
        patch:
            tags:
                - Players
            summary: Update a player
            responses:
                200:
                    description: The updated player
        delete:
            tags:
                - Players
            summary: Delete a player
            responses:
                204:
                    description: The player was deleted
    /players/{slug}:
        get:
            tags:
                - Players
            summary: Returns single player by slug (e.g. firstName-lastName)
            parameters:
                - name: slug
                  in: path
                  description: Slug of the player's name (e.g. firstName-lastName)
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                200:
                    description: The player by slug
                    schema:
                    $ref: '#/definitions/PlayersResponse'
    /players/captain:
        get:
            tags:
                - Players
            summary: Returns current Team Captain
            produces:
                - application/json
            responses:
                200:
                    description: Current Team Captain
                    schema:
                        $ref: '#/definitions/PlayersResponse'
    /players/vicecaptain:
        get:
            tags:
                - Players
            summary: Returns current Team Vice-Captain
            produces:
                - application/json
            responses:
                200:
                    description: Current Team Vice Captain
                    schema:
                        $ref: '#/definitions/PlayersResponse'
    /players/loan:
        get:
            tags:
                - Players
            summary: Returns all loan players
            produces:
                - application/json
            responses:
                200:
                    description: List of all players who are either loaned into or out of the club
                    schema:
                        $ref: '#/definitions/PlayersResponse'
    /players/loan/in:
        get:
            tags:
                - Players
            summary: Returns all loan players
            produces:
                - application/json
            responses:
                200:
                    description: List of players who are loaned into the club from other clubs
                    schema:
                        $ref: '#/definitions/PlayersResponse'
    /players/loan/out:
        get:
            tags:
                - Players
            summary: Returns all loan players
            produces:
                - application/json
            responses:
                200:
                    description: List of players who are loaned out of the club to other clubs
                    schema:
                        $ref: '#/definitions/PlayersResponse'
    /staff:
        get:
            tags:
                - Staff
            summary: Get all staff
            responses:
                200:
                    description: A list of staff
                    schema:
                        $ref: '#/definitions/StaffResponse'
        post:
            tags:
                - Staff
            summary: Create a new staff member
            responses:
                201:
                    description: The created staff member
                    schema:
                        $ref: '#/definitions/StaffResponse'
        patch:
            tags:
                - Staff
            summary: Update a staff member
            responses:
                200:
                    description: The updated staff member
                    schema:
                        $ref: '#/definitions/StaffResponse'
        delete:
            tags:
                - Staff
            summary: Delete a staff member
            responses:
                204:
                    description: The staff member was deleted
                    schema:
                        $ref: '#/definitions/StaffResponse'
    /staff/{slug}:
        get:
            tags:
                - Staff
            summary: Get a staff member by slug
            parameters:
                - in: path
                  name: slug
                  required: true
                  type: string
            responses:
                200:
                    description: The staff member
                    schema:
                        $ref: '#/definitions/StaffResponse'
